"""Reviewed, static service information in the four supported languages."""
from html import escape
import json,re
COPY={
'shipping': ['Du bezahlst den Versand zu Mujitech. Den Rückversand nach der Reparatur übernimmt Mujitech. Bitte erst nach Bestätigung der Versandadresse einsenden.','Vous payez l’envoi à Mujitech. Mujitech prend en charge le retour après la réparation. Attendez la confirmation de l’adresse avant d’envoyer votre appareil.','Paghi la spedizione a Mujitech. Mujitech paga la spedizione di ritorno dopo la riparazione. Attendi la conferma dell’indirizzo prima di spedire il dispositivo.','You pay for shipping to Mujitech. Mujitech pays for return shipping after the repair. Wait for confirmation of the shipping address before sending your device.'],
'estimate':['Preis und Dauer hängen von Modell, Defekt und Ersatzteilen ab. Nach der Prüfung stimmen wir Kosten, Umfang und Zeitplan mit dir ab. Die Reparatur beginnt erst nach deiner Freigabe.','Le prix et le délai dépendent du modèle, de la panne et des pièces. Après examen, nous convenons avec vous du coût, des travaux et du délai. La réparation commence uniquement après votre accord.','Prezzo e tempi dipendono dal modello, dal guasto e dai ricambi. Dopo la verifica concordiamo costi, intervento e tempi. La riparazione inizia solo dopo il tuo consenso.','Price and timing depend on the model, fault and parts. After inspection, we agree the cost, work and timing with you. Repairs only start with your approval.'],
'clear':['Klare Absprachen. Persönlicher Kontakt.','Des conditions claires. Un contact personnel.','Accordi chiari. Contatto personale.','Clear agreements. Personal contact.'],
'cost':['Kosten vor der Reparatur klären','Un coût convenu avant la réparation','Costi concordati prima della riparazione','Agree the cost before repairs'],
'guarantee':['6 Monate Reparaturgarantie','Garantie réparation de 6 mois','Garanzia riparazioni di 6 mesi','6-month repair warranty'],
'guarantee-text':['Auf ausgetauschte Hardware gewährt Mujitech 6 Monate Garantie. Die Bedingungen findest du bei den Reparaturinformationen.','Mujitech offre une garantie de 6 mois sur les composants remplacés. Consultez les informations sur les réparations pour les conditions.','Mujitech offre 6 mesi di garanzia sui componenti sostituiti. Consulta le informazioni sulle riparazioni per le condizioni.','Mujitech provides a 6-month warranty on replaced hardware. See the repair information for the terms.'],
'return':['Kostenloser Rückversand','Retour sans frais','Spedizione di ritorno gratuita','Free return shipping'],
'contact':['Persönlich erreichbar','Un contact direct','Contatto diretto','Contact us directly'],
'contact-text':['Fragen zu Gerät, Reparatur oder Website? Kontaktiere uns direkt per Telefon, WhatsApp oder E-Mail. Geräteübergabe in Abtwil SG nach Termin.','Une question sur un appareil, une réparation ou un site web ? Contactez-nous par téléphone, WhatsApp ou e-mail. Remise d’appareils à Abtwil SG sur rendez-vous.','Domande su un dispositivo, una riparazione o un sito web? Contattaci per telefono, WhatsApp o e-mail. Consegna dispositivi ad Abtwil SG su appuntamento.','Questions about a device, repair or website? Contact us by phone, WhatsApp or email. Device handover in Abtwil SG by appointment.'],
'process':['So läuft deine Reparatur ab','Le déroulement de votre réparation','Come funziona la riparazione','How your repair works'],
'step1':['1. Gerät und Defekt beschreiben','1. Décrivez l’appareil et la panne','1. Descrivi dispositivo e guasto','1. Describe the device and fault'],
'step1-text':['Nenne das Modell und beschreibe das Problem. Wir klären zuerst, ob die Reparatur möglich ist und wie die Übergabe oder Einsendung abläuft.','Indiquez le modèle et décrivez le problème. Nous vérifions d’abord si la réparation est possible et organisons la remise ou l’envoi.','Indica il modello e descrivi il problema. Verifichiamo prima se la riparazione è possibile e concordiamo consegna o spedizione.','Tell us the model and describe the problem. We first check whether repair is possible and agree handover or shipping.'],
'step2':['2. Prüfung und Freigabe','2. Examen et accord','2. Verifica e consenso','2. Inspection and approval'],
'step3':['3. Reparatur und Rückgabe','3. Réparation et retour','3. Riparazione e restituzione','3. Repair and return'],
'step3-text':['Nach der vereinbarten Reparatur organisieren wir die Rückgabe oder den Rückversand. Kosten und Termin für den Versand zu uns klärst du vorab mit uns.','Après la réparation convenue, nous organisons la remise ou le retour par poste. Convenez avec nous des modalités d’envoi avant de nous adresser l’appareil.','Dopo la riparazione concordata organizziamo la restituzione o il ritorno per posta. Concorda prima con noi le modalità di spedizione.','After the agreed repair, we arrange collection or return shipping. Agree the shipping arrangements with us before sending the device.'],
'prepare':['Vor der Übergabe oder dem Versand','Avant la remise ou l’envoi','Prima della consegna o spedizione','Before handover or shipping'],
'prepare-text':['Erstelle nach Möglichkeit eine Datensicherung, entferne SIM-Karte und Zubehör, soweit nicht anders vereinbart, und verpacke das Gerät geschützt. Schicke keine Passwörter im Formular. Bei aufgeblähtem Akku oder stark beschädigter Batterie zuerst Kontakt aufnehmen und nicht ohne Abklärung versenden.','Si possible, sauvegardez vos données, retirez la carte SIM et les accessoires sauf accord contraire et protégez l’appareil dans son emballage. N’envoyez aucun mot de passe dans le formulaire. Si la batterie est gonflée ou très endommagée, contactez-nous avant tout envoi.','Se possibile, esegui un backup, rimuovi SIM e accessori salvo diverso accordo e imballa il dispositivo con protezione. Non inviare password nel modulo. Se la batteria è gonfia o gravemente danneggiata, contattaci prima di spedire.','Back up your data if possible, remove the SIM and accessories unless otherwise agreed, and pack the device securely. Do not send passwords in the form. If a battery is swollen or badly damaged, contact us before shipping.'],
'repairs':['Welche Reparatur passt zu deinem Problem?','Quelle réparation convient à votre problème ?','Quale riparazione serve al tuo dispositivo?','Which repair does your device need?'],
'display':['iPhone- und Handy-Display reparieren','Réparation écran iPhone et smartphone','Riparazione schermo iPhone e smartphone','iPhone and phone screen repair'],
'display-text':['Gesprungenes Glas, Bildfehler oder ein Touchscreen ohne Reaktion? Nenne dein genaues Modell und ob Bild und Touch noch funktionieren. Wir prüfen das benötigte Ersatzteil und besprechen Preis und Ausführung mit dir.','Vitre cassée, défaut d’affichage ou écran tactile sans réaction ? Indiquez le modèle exact et si l’image et le tactile fonctionnent encore. Nous vérifions la pièce nécessaire et convenons du prix et de l’intervention.','Vetro rotto, problemi di immagine o touch non funzionante? Indica il modello esatto e se immagine e touch funzionano ancora. Verifichiamo il ricambio necessario e concordiamo prezzo e intervento.','Cracked glass, display faults or an unresponsive touchscreen? Tell us the exact model and whether the display and touch still work. We check the required part and agree the price and repair with you.'],
'battery':['iPhone- und Smartphone-Akku wechseln','Remplacement batterie iPhone et smartphone','Sostituzione batteria iPhone e smartphone','iPhone and smartphone battery replacement'],
'battery-text':['Kurze Akkulaufzeit oder unerwartetes Ausschalten? Beschreibe die Symptome und dein Modell. Wir prüfen, ob ein Akkutausch sinnvoll ist; ähnliche Probleme können auch andere Ursachen haben.','Autonomie réduite ou extinction inattendue ? Décrivez les symptômes et le modèle. Nous vérifions si un remplacement de batterie est adapté : d’autres causes peuvent produire les mêmes symptômes.','Autonomia ridotta o spegnimenti improvvisi? Descrivi sintomi e modello. Verifichiamo se serve sostituire la batteria: gli stessi problemi possono avere altre cause.','Short battery life or unexpected shutdowns? Describe the symptoms and model. We check whether battery replacement is appropriate; similar symptoms may have other causes.'],
'computer':['Laptop- und PC-Reparatur','Réparation PC et ordinateur portable','Riparazione PC e portatili','Laptop and PC repair'],
'computer-text':['Computer startet nicht, Laptop-Display defekt oder Gerät sehr langsam? Wir prüfen Hardware und besprechen mögliche Reparaturen, Reinigung sowie SSD- und RAM-Upgrades. Modell, Fehlerbild und vorhandene Datensicherung helfen bei der Anfrage.','Votre ordinateur ne démarre pas, l’écran est cassé ou le PC est très lent ? Nous examinons le matériel et discutons réparation, nettoyage et mises à niveau SSD ou RAM. Indiquez le modèle, les symptômes et si une sauvegarde existe.','Il computer non si avvia, lo schermo è rotto o il PC è molto lento? Verifichiamo l’hardware e discutiamo riparazione, pulizia e aggiornamenti SSD o RAM. Indica modello, sintomi e disponibilità di un backup.','Computer will not start, laptop screen broken or PC running slowly? We inspect the hardware and discuss repair, cleaning and SSD or RAM upgrades. Include the model, symptoms and whether you have a backup.'],
'ask':['Unverbindlich anfragen','Demander sans engagement','Richiedi senza impegno','Send a non-binding enquiry'],
'help':['Computerhilfe und Handy-Einrichtung: gezielt starten','Assistance informatique et configuration smartphone','Assistenza computer e configurazione smartphone','Computer help and smartphone setup'],
'help-text':['Beschreibe, was nicht funktioniert und welches Gerät du nutzt. Bei der Handy-Einrichtung helfen wir mit Kontakten, E-Mail und Apps. Bei langsamen Computern prüfen wir geeignete Optimierungen; bei WLAN-Problemen klären wir zuerst Router, Geräte und Verbindung. Du gibst Zugangsdaten selbst ein.','Décrivez le problème et l’appareil utilisé. Nous vous aidons à configurer contacts, e-mail et applications sur votre smartphone. Pour un PC lent, nous examinons les améliorations possibles ; pour le Wi-Fi, nous vérifions d’abord routeur, appareils et connexion. Vous saisissez vous-même vos identifiants.','Descrivi il problema e il dispositivo. Ti aiutiamo a configurare contatti, e-mail e app sul telefono. Per un PC lento verifichiamo le ottimizzazioni adatte; per il Wi-Fi controlliamo prima router, dispositivi e connessione. Inserisci personalmente le tue credenziali.','Describe the problem and device. We help set up contacts, email and apps on your phone. For slow computers, we assess suitable improvements; for Wi-Fi issues, we first check the router, devices and connection. You enter your own login details.'],
'web':['Was eine gute Firmenwebsite leisten soll','Ce qu’un site professionnel doit apporter','Cosa deve offrire un sito aziendale','What a business website should do'],
'web-text':['Deine Besucher sollen Leistungen, Preise und Kontakt schnell finden – besonders auf dem Handy. Wir planen eine klare Seitenstruktur, verständliche Texte, passende Kontaktmöglichkeiten und technische SEO-Grundlagen. Mehrsprachigkeit und Wartung werden passend zum Projekt vereinbart.','Vos visiteurs doivent trouver rapidement prestations, prix et contact, surtout sur mobile. Nous prévoyons une structure claire, des textes compréhensibles, des moyens de contact adaptés et les bases techniques du référencement. Langues et maintenance sont convenues selon le projet.','I visitatori devono trovare rapidamente servizi, prezzi e contatti, soprattutto sul telefono. Progettiamo struttura chiara, testi comprensibili, contatti adatti e basi tecniche SEO. Lingue e manutenzione vengono concordate in base al progetto.','Visitors should quickly find your services, prices and contact details, especially on mobile. We plan a clear page structure, understandable copy, suitable contact options and technical SEO foundations. Languages and maintenance are agreed for each project.'],
'web-ready':['Was du für die erste Anfrage brauchst','Pour votre première demande','Cosa serve per la prima richiesta','What to include in your first enquiry'],
'web-ready-text':['Beschreibe dein Unternehmen und das Ziel der Website. Ein bestehender Link oder Beispiele sind hilfreich, aber nicht erforderlich. Du musst noch kein Paket wählen. Danach besprechen wir Umfang, Inhalte, Zuständigkeiten und Offerte.','Décrivez votre entreprise et l’objectif du site. Un lien existant ou des exemples sont utiles, mais facultatifs. Vous n’avez pas besoin de choisir une formule. Nous discutons ensuite du périmètre, des contenus, des responsabilités et du devis.','Descrivi la tua attività e l’obiettivo del sito. Un link esistente o esempi sono utili ma facoltativi. Non devi scegliere subito un pacchetto. Poi discutiamo contenuti, responsabilità, intervento e preventivo.','Describe your business and the website’s goal. An existing link or examples are useful but optional. You do not need to choose a package yet. We then discuss scope, content, responsibilities and a quote.'],
'purchase':['So kaufst du ein Gerät bei Mujitech','Acheter un appareil chez Mujitech','Come acquistare un dispositivo da Mujitech','How to buy a device from Mujitech'],
'purchase-text':['Frage das gewünschte Gerät per WhatsApp oder E-Mail an. Wir bestätigen die aktuelle Verfügbarkeit, den Zustand, Lieferumfang und die Zahlungsabwicklung. Deine Anfrage ist noch keine Bestellung. Der Versand von gekauften Geräten innerhalb der Schweiz ist kostenlos.','Demandez l’appareil souhaité par WhatsApp ou e-mail. Nous confirmons disponibilité, état, accessoires inclus et paiement. Votre demande n’est pas encore une commande. La livraison des appareils achetés est gratuite en Suisse.','Richiedi il dispositivo via WhatsApp o e-mail. Confermiamo disponibilità, condizioni, accessori inclusi e pagamento. La richiesta non costituisce ancora un ordine. La spedizione dei dispositivi acquistati è gratuita in Svizzera.','Enquire about the device by WhatsApp or email. We confirm current availability, condition, included items and payment arrangements. Your enquiry does not place an order. Purchased devices ship free within Switzerland.'],
'conditions':['Garantie, Lieferung und Rückgabe','Garantie, livraison et retour','Garanzia, consegna e resi','Warranty, delivery and returns'],
'conditions-text':['Die Gerätegarantie steht beim jeweiligen Angebot. Liefertermin, Garantiebedingungen und mögliche Rückgabe vereinbaren wir vor dem Kauf; eine Rückgabefrist wird hier nicht pauschal zugesagt. Bei Fragen oder einem Problem mit dem Gerät kontaktiere Mujitech direkt.','La garantie figure dans chaque offre. Avant l’achat, nous convenons du délai de livraison, des conditions de garantie et des possibilités de retour. Aucun délai de retour général n’est promis ici. En cas de question ou de problème, contactez Mujitech.','La garanzia è indicata nella singola offerta. Prima dell’acquisto concordiamo consegna, condizioni di garanzia e possibilità di reso. Non viene promessa una scadenza generale per i resi. Per domande o problemi contatta Mujitech.','The warranty is stated in each offer. Before purchase, we agree delivery timing, warranty terms and any return arrangements; no general return period is promised here. Contact Mujitech with questions or device issues.'],
'sell':['Gebrauchtes Gerät verkaufen: diese Angaben helfen','Vendre un appareil d’occasion : les informations utiles','Vendere un dispositivo usato: informazioni utili','Selling a used device: useful information'],
'sell-text':['Nenne Marke, Modell, Speicher und Zustand sowie bekannte Schäden. Fotos helfen bei der Einschätzung. Die Bewertung ist unverbindlich; Zustand und endgültiger Ankaufspreis werden vor dem Abschluss geprüft und vereinbart. Persönliche Daten und Kontoverknüpfungen entfernst du vor einer vereinbarten Übergabe.','Indiquez marque, modèle, stockage, état et dommages connus. Des photos facilitent l’estimation. Celle-ci est sans engagement ; état et prix final sont vérifiés et convenus avant la vente. Retirez vos données personnelles et comptes avant la remise convenue.','Indica marca, modello, memoria, condizioni e danni noti. Le foto aiutano la valutazione. La stima non è vincolante; condizioni e prezzo finale vengono verificati e concordati prima della vendita. Rimuovi dati personali e account prima della consegna concordata.','Include brand, model, storage, condition and known damage. Photos help with the estimate. The estimate is non-binding; condition and final purchase price are checked and agreed before the sale. Remove personal data and linked accounts before the agreed handover.'],
}
IDX={'de':0,'fr':1,'it':2,'en':3}
def apply_quality(data,f,l,path_for,canonical):
 def c(k):return escape(COPY[k][IDX[l]])
 def card(h,p,ident=''):return f'<article class="quality-card"'+(f' id="{ident}"' if ident else '')+f'><h3>{c(h)}</h3><p>{c(p)}</p></article>'
 def section(h,body,ident=''):return f'<section class="quality-section"'+(f' id="{ident}"' if ident else '')+f'><div class="wrap"><h2>{c(h)}</h2>{body}</div></section>'
 sections=[]
 if f=='index.html':
  data=data.replace('<h4>','<h3>').replace('</h4>','</h3>')
  body=card('cost','estimate')+card('guarantee','guarantee-text')+card('return','shipping')
  section_html=section('clear','<div class="quality-grid">'+body+'</div>')
  # Put meaningful assurances before service listings, rather than at the footer.
  data=data.replace('<!-- LEISTUNGEN -->',section_html+'<!-- LEISTUNGEN -->',1) if '<!-- LEISTUNGEN -->' in data else data.replace('</main>',section_html+'</main>',1)
 if f in ['reparaturen.html','reparatur-schweiz.html']:
  body=card('step1','step1-text')+card('step2','estimate')+card('step3','shipping')
  sections.append(section('process','<div class="quality-grid">'+body+'</div><div class="quality-note"><h3>'+c('prepare')+'</h3><p>'+c('prepare-text')+'</p></div>','reparatur-ablauf'))
 if f=='reparaturen.html':
  body=''
  for h,p,ident in [('display','display-text','displaytausch'),('battery','battery-text','akkutausch'),('computer','computer-text','computer-reparatur')]:
   body+=card(h,p,ident)
  sections.insert(0,section('repairs','<div class="quality-grid">'+body+'</div><p><a class="cta" href="'+path_for('anfrage.html',l)+'">'+c('ask')+'</a></p>'))
 if f=='privatkunden.html':sections.append(section('help','<p class="quality-lead">'+c('help-text')+'</p>'))
 if f=='websites.html':sections.append(section('web','<p class="quality-lead">'+c('web-text')+'</p><div class="quality-note"><h3>'+c('web-ready')+'</h3><p>'+c('web-ready-text')+'</p></div>'))
 if f in ['shop.html','iphone-14-pro-max.html','iphone-17-pro-max.html']:
  sections.append(section('purchase','<p class="quality-lead">'+c('purchase-text')+'</p><div class="quality-note"><h3>'+c('conditions')+'</h3><p>'+c('conditions-text')+'</p><a href="'+path_for('rechtliches.html',l)+'">'+{'de':'Rechtliches und Datenschutz','fr':'Mentions légales et confidentialité','it':'Note legali e privacy','en':'Legal and privacy information'}[l]+'</a></div>'))
 if f=='geraet-verkaufen.html':sections.append(section('sell','<p class="quality-lead">'+c('sell-text')+'</p>'))
 if f in ['anfrage.html','reparaturanfrage.html']:
  sections.append(section('cost','<p class="quality-lead">'+c('estimate')+'</p><div class="quality-note"><h3>'+c('return')+'</h3><p>'+c('shipping')+'</p></div>'))
 if sections:data=data.replace('</main>',''.join(sections)+'</main>',1)
 if f in ['iphone-14-pro-max.html','iphone-17-pro-max.html']:
  is14=f=='iphone-14-pro-max.html';name='Apple iPhone '+('14 Pro Max 256 GB Space Black' if is14 else '17 Pro Max 512 GB '+{'de':'Silber','fr':'argent','it':'argento','en':'silver'}[l])
  image='iphone-14-pro-max.jpg' if is14 else 'iphone-17-pro-max-silber.png'
  desc=re.search(r'<meta name="description" content="([^"]+)"',data)
  product={'@context':'https://schema.org','@type':'Product','@id':canonical(f,l)+'#product','name':name,'image':'https://mujitech.ch/'+image,'brand':{'@type':'Brand','name':'Apple'},'offers':{'@type':'Offer','url':canonical(f,l),'priceCurrency':'CHF','price':'460.00' if is14 else '1000.00','itemCondition':'https://schema.org/UsedCondition','seller':{'@id':'https://mujitech.ch/#organization'}}}
  product['description']={'de':'Gebrauchtes, geprüftes iPhone mit 100 % Akkukapazität und 12 Monaten Mujitech Hardwaregarantie.','fr':'iPhone d’occasion contrôlé, avec capacité de batterie de 100 % et garantie matérielle Mujitech de 12 mois.','it':'iPhone usato verificato, con capacità batteria del 100 % e garanzia hardware Mujitech di 12 mesi.','en':'Tested used iPhone with 100% battery capacity and a 12-month Mujitech hardware warranty.'}[l]
  product['offers']['shippingDetails']={'@type':'OfferShippingDetails','shippingDestination':{'@type':'DefinedRegion','addressCountry':'CH'},'shippingRate':{'@type':'MonetaryAmount','value':'0.00','currency':'CHF'}}
  # Stock is confirmed personally; avoid stale inventory and invented return terms.
  data=data.replace('</head>','<script type="application/ld+json">'+json.dumps(product,ensure_ascii=False)+'</script></head>',1)
 return data
